### ISSUE TITLE
Functionality Overview Checklist

### ISSUE THREAD

**Issue by AlexKiselich** [AlexKiselich/b2-final-starter-7#11]
**Functionality Overview**
- [x] A Coupon belongs to a Merchant
- [x] An Invoice optionally belongs to a Coupon. An invoice may only have one coupon.
Note: When creating this new association on Invoice, your existing tests will fail unless the association is optional. Use [these guides](https://guides.rubyonrails.org/association_basics.html#optional) as a reference.​
- [x] Merchants have full CRUD functionality over their coupons with criteria/restrictions defined below:
- [x] A merchant can have a maximum of 5 activated coupons in the system at one time.
- [x] A merchant cannot delete a coupon, rather they can activate/deactivate them.
- [x] A Coupon has a name, unique code (e.g. “BOGO50”), and either percent-off or dollar-off value. The coupon’s code must be unique in the whole database.
- [x] If a coupon’s dollar value (ex. “$10 off”) exceeds the total cost of that merchant’s items on the invoice, the grand total for that merchant’s items should then be $0. (In other words, the merchant will never owe money to a customer.)
- [x] A coupon code from a Merchant only applies to Items sold by that Merchant.
